# Cleaning Customer Call List

### Tasks
   - drop duplicates
   - Clean unwanted non-alphanumeric(symbols)
   - Standardizing phone numbers
   - Multiple columns creation based on one single column
   - Remove null value
   - drop unwanted rows

In [1]:
import pandas as pd

In [2]:
# reading excel file
df = pd.read_excel(r"files\customer-call-list.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [3]:
# dropping duplicate rows
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

**NOTE:** dropping duplicates is the first stage of cleaning.

In [4]:
# dropping unuseful column
df = df.drop('Not_Useful_Column', axis=1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

**NOTE:** Dropping unwanted columns make the dataset smaller.

In [5]:
# cleaning names that have garbage with them
df["Last_Name"] = df["Last_Name"].str.strip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

**NOTE:** strip() function is used to remove any leading, and trailing unwanted symbol. In our case, removes any leading or trailing characters **`'1', '2', '3', '.', '_', or '/'`** from the **`Last_Name`** column.

**`It is not necessary to match the whole pattern, but also it removes leading and trailing characaters if they are present in the argument`**

In [6]:
# Task : Standardizing Phone numbers
# TO DO : remove non-alphanumeric characters
# TO DO : convert column values into string
# TO DO : Format Numbers

# removes non-alphanumeric and convert each value into string
phone_col = df["Phone_Number"].str.replace("[^a-zA-Z0-9]", "", regex=True).astype(str)

# formating phone numbers
df["Phone_Number"] = phone_col.apply(lambda x: f"{x[:3]}-{x[3:6]}-{x[6:]}")

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

**NOTE:**
   - ***str.replace():*** Replace non-alphanumeric characters with an empty space using a regular expression.
   - ***astype(str):*** Converts the column values to strings in one step.
   - ***apply():*** Formats the phone numbers with hyphens.

**Similar Code:**
   - Step1: Replace non-alphanumeric characters (Symbols)
   - Step2: Convert column values into string
   - Step3: Format the phone numbers

```python
# removing symbols(non-alphanumeric) inside the numbers
df["Phone_Number"] = df["Phone_Number"].str.replace("[^a-zA-Z0-9]", "")

# converting column values into string
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))

# formating numbers
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[:3] + "-" + x[3:6] + "-" + x[6:])
```

**One Line Approach:**
```python
df["Phone_Number"] = df["Phone_Number"].str.replace("[^a-zA-Z0-9]", "", regex=True).astype(str).apply(lambda x: f"{x[:3]}-{x[3:6]}-{x[6:]}")
```

In [7]:
# cleaning null values of the phone number columns
df["Phone_Number"] = df["Phone_Number"].str.replace(r"(nan--|Na--)", "", regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

**NOTE:** **`r"(nan--|Na--)"`** is a regular expression that matches either "nan--" or "Na--". If it matches then replace them with an empty string.

**Similar Code:**
```python
df["Phone_Number"] = df["Phone_Number"].str.replace("nan--", "")
df["Phone_Number"] = df["Phone_Number"].str.replace("Na--", "")
```

**One Line Approach:**
```python
df["Phone_Number"] = df["Phone_Number"].str.replace(r"(nan--|Na--)", "", regex=True)
```

In [8]:
""" split column (create multiple columns based on one column) """

# creating new columns and assigining values
df[["Street", "State", "Zip_Code"]] = df["Address"].str.split(", ", 2, expand=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

**NOTE:** split **`Address`** column into 3 division where the second argument indicate the max split. Then create three new columns and assign the splitted values in those columns

In [9]:
# Task: standardizing multiple columns valu
# TO DO : Replace The values
df[["Paying Customer", "Do_Not_Contact"]] = df[["Paying Customer", "Do_Not_Contact"]].replace({"Yes":"Y", "No": "N"})
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

**NOTE:** We can replace multiple items by passing a dictionary in the replace() function. By accessing multiple columns, we can replce the same items from each column

**Similar Code:**
```python
df["Paying Customer"] = df["Paying Customer"].str.replace("Yes", "Y")
df["Paying Customer"] = df["Paying Customer"].str.replace("No", "N")

df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("Yes", "Y")
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("No", "N")
```

**One Line Approach:**
```python
df[["Paying Customer", "Do_Not_Contact"]] = df[["Paying Customer", "Do_Not_Contact"]].replace({"Yes":"Y", "No": "N"})
```

In [10]:
# clean up NaN data from the dataset
df = df.fillna("")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

**NOTE:** we can not use **`replace()`** function to replace NaN values in the column. Because **`replace()`** is used to replace a string. Since NaN is not a string, we have to use the **`fillna()`**

In [11]:
# filtering rows
for item in df.index:
    if df.at[item, "Do_Not_Contact"] == "Y":
        df.drop(item, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

**NOTE:** We can use conditional selection technique to filter rows.

**Example:**
```python
df = df[df["Do_Not_Contact"] != "Y"]
```

In [12]:
# filtering rows
df = df[df["Phone_Number"] != ""]
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

**NOTE:** Conditional Selection

**Similar Code:**
```python
for item in df.index:
    if df.at[item, "Phone_Number"] == "":
        df.drop(item, inplace=True)
```

In [13]:
# final touch
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [14]:
df.to_excel(r"files\customer-call-list-cleaned.xlsx")

## This NoteBook is created by Tshihab07, Dept. of Computer Science and Engineering